{{- if or .Values.encryption.key .Values.database.postgres.password .Values.license.activationKey .Values.license.certificate .Values.smtp.password .Values.queue.redis.password }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "n8n-custom.fullname" . }}-secrets
  labels:
    {{- include "n8n-custom.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.encryption.key }}
  encryption-key: {{ .Values.encryption.key | b64enc | quote }}
  {{- else }}
  encryption-key: {{ randAlphaNum 32 | b64enc | quote }}
  {{- end }}
  {{- if and (eq .Values.database.type "postgres") .Values.database.postgres.password (not .Values.database.postgres.existingSecret) }}
  db-password: {{ .Values.database.postgres.password | b64enc | quote }}
  {{- end }}
  {{- if and .Values.license.activationKey (not .Values.license.existingSecret) }}
  license-activation-key: {{ .Values.license.activationKey | b64enc | quote }}
  {{- end }}
  {{- if and .Values.license.certificate (not .Values.license.existingSecret) }}
  license-certificate: {{ .Values.license.certificate | b64enc | quote }}
  {{- end }}
  {{- if and .Values.smtp.password (not .Values.smtp.existingSecret) }}
  smtp-password: {{ .Values.smtp.password | b64enc | quote }}
  {{- end }}
  {{- if and .Values.queue.enabled .Values.queue.redis.password (not .Values.queue.redis.existingSecret) }}
  redis-password: {{ .Values.queue.redis.password | b64enc | quote }}
  {{- end }}
{{- end }}
